---
- name: Test the website
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Check port 80 is listening on managed node
    wait_for:
      port: 80
      state: started
      timeout: 3

  - name: Verify apache is available remotely
    uri:
      url: "http://{{ ansible_host }}/index.html"
    delegate_to: localhost

  - name: Stat apache2
    stat:
      path: /usr/sbin/apache2
    register: i

  - name: Fail if apache2 doesnt exist
    assert:
      that:
        - "i.stat.exists"
      fail_msg: "/usr/sbin/apache2 does not exist"
      success_msg: "/usr/sbin/apache2 exists"

  - name: Check Stat index.html
    stat:
      path: /var/www/html/index.html
    register: a

  - name: confirm that index.html exists & owned by root
    assert:
      that:
        - "a.stat.exists"
        - "a.stat.pw_name == 'root'"
      fail_msg: "index /var/www/html/index.html does not exist or is not owned by root"
      success_msg: "/var/www/html/index.html exists and is owned by root"
